In [1]:
import pandas as pd

In [2]:
file_path = 'Titanic.csv'
def read_file(file_path):
    return pd.read_csv(file_path).head()
read_file(file_path)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
# df = pd.read_csv('Titanic.csv')
# cols = ['PassengerId','Name','Ticket']
# df.drop(cols, axis= 1, inplace= True)
# df.head()

In [4]:
from config import COLS_DROP
from preprocessing import drop_cols
df = pd.read_csv('Titanic.csv')
df=drop_cols(df,COLS_DROP)
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S

In [5]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S

In [6]:
dtypes = df.dtypes
nunique = df.nunique()
pd.DataFrame({"dtypes":dtypes, "nunique": nunique }).T

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
dtypes,int64,int64,object,float64,int64,int64,float64,object,object
nunique,2,3,2,88,7,7,248,147,3

In [7]:
cat_cols= ["Survived","Pclass","Sex","SibSp","Parch","Embarked"]
df[cat_cols] = df[cat_cols].astype("category")

In [8]:
def get_type_Info(df):
    return pd.DataFrame({"dtypes":df.dtypes, "nunique": df.nunique() }).T

In [9]:
get_type_Info(df)

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
dtypes,category,category,category,float64,category,category,float64,object,category
nunique,2,3,2,88,7,7,248,147,3

In [10]:
df.select_dtypes("category")

    Survived Pclass     Sex SibSp Parch Embarked
0          0      3    male     1     0        S
1          1      1  female     1     0        C
2          1      3  female     0     0        S
3          1      1  female     1     0        S
4          0      3    male     0     0        S
..       ...    ...     ...   ...   ...      ...
886        0      2    male     0     0        S
887        1      1  female     0     0        S
888        0      3  female     1     2        S
889        1      1    male     0     0        C
890        0      3    male     0     0        Q

[891 rows x 6 columns]

In [11]:
df.head()

  Survived Pclass     Sex   Age SibSp Parch     Fare Cabin Embarked
0        0      3    male  22.0     1     0   7.2500   NaN        S
1        1      1  female  38.0     1     0  71.2833   C85        C
2        1      3  female  26.0     0     0   7.9250   NaN        S
3        1      1  female  35.0     1     0  53.1000  C123        S
4        0      3    male  35.0     0     0   8.0500   NaN        S

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    category
 1   Pclass    891 non-null    category
 2   Sex       891 non-null    category
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    category
 5   Parch     891 non-null    category
 6   Fare      891 non-null    float64
 7   Cabin     204 non-null    object
 8   Embarked  889 non-null    category
dtypes: category(6), float64(2), object(1)
memory usage: 27.4+ KB

In [13]:
null = df.isnull().sum()
ratio = (null / 891)*100
ratio

Survived     0.000000
Pclass       0.000000
Sex          0.000000
Age         19.865320
SibSp        0.000000
Parch        0.000000
Fare         0.000000
Cabin       77.104377
Embarked     0.224467
dtype: float64

In [14]:
df = df.dropna(subset=['Embarked'])

In [15]:
df = df.drop("Cabin",axis=1)

In [16]:
# df.describe()
median = df['Age'].median()
df['Age']  = df['Age'].fillna(median, inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_24424\143703380.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age']  = df['Age'].fillna(median, inplace=True)

In [17]:
null = df.isnull().sum()
ratio = (null / 891)*100
pd.DataFrame({"null":null, "ratio": ratio }).T

       Survived  Pclass  Sex         Age  SibSp  Parch  Fare  Embarked
null        0.0     0.0  0.0  889.000000    0.0    0.0   0.0       0.0
ratio       0.0     0.0  0.0   99.775533    0.0    0.0   0.0       0.0