In [4]:
import numpy as np

In [10]:
def init_w(shape,value):
    return np.full(shape,value)

In [15]:
# init_w((3,4),5)

ones =init_w((3,4),1)
ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [16]:
angle=np.arange(0,361,90)
angle

array([  0,  90, 180, 270, 360])

In [18]:
np.random.random((3,3))

array([[0.22786294, 0.05338917, 0.30147969],
       [0.73350181, 0.11736298, 0.45252569],
       [0.86541886, 0.35748128, 0.48030996]])

In [19]:
np.random.randint(0,11,(5,5))

array([[ 1,  0,  4,  7,  2],
       [ 3,  3, 10,  7,  4],
       [ 0,  8,  9,  0,  8],
       [ 8,  0,  8,  3,  3],
       [ 4,  2,  6,  9,  8]], dtype=int32)

In [20]:
a=['nada','ali','aya']
np.random.choice(a,size=(3,5))

array([['aya', 'nada', 'aya', 'nada', 'nada'],
       ['ali', 'nada', 'aya', 'ali', 'aya'],
       ['nada', 'ali', 'nada', 'nada', 'ali']], dtype='<U4')

In [23]:
mat1 =np.ones((3,4))
print(mat1)
print("="*20)
mat2 =np.zeros((5,3))
print(mat2)
np.savez('np_file.npz',cat=mat1,dog =mat2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
====================
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

In [24]:
m1 =np.array([[1,2,3],
             [0,0,0]])
m2 =np.array([[4,5,6],
             [1,1,1]])
new_mat=np.vstack((m1,m2))
new_mat

array([[1, 2, 3],
       [0, 0, 0],
       [4, 5, 6],
       [1, 1, 1]])

In [26]:
v1 =np.array([1,2,3,4,5])
v2 =np.array([2,2,6,8,7])
v1==v2

array([False,  True, False, False, False])

In [28]:
v =np.array([1,2,3,4,5,0])
# np.all(v >=1)
np.any(v >=1)

np.True_

In [30]:
v1 =np.array([1,2,3,4,5])
v2 =np.array([2,2,6,8,7])
# np.isclose(v1,v2,atol =1)
np.allclose(v1,v2,atol =1)

False

In [35]:
v=np.array([2,4,3,7,4])
condition = v >=4
v[condition] = -1
print(v)

[ 2 -1  3 -1 -1]

In [36]:
v=np.array([2,4,3,7,4])
c=2
sum=v+c
print(sum)

[4 6 5 9 6]

In [2]:
import pandas as pd

In [39]:
s=pd.Series([1,2,3,4,5])
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [43]:
data =[[1,444,'abc'],
       [2,555,'def'],
       [3,666,'ski'],
       [4,444,'xyz']]

# df= pd.DataFrame(data,columns=["id","sal","dep"])
# df

data2={'id':[1,2,3,4],
      'sal':[444,555,666,444],
      'dep':['abc','def','ghi','xyz']}

df = pd.DataFrame(data2)
type(df)
df

   id  sal  dep
0   1  444  abc
1   2  555  def
2   3  666  ghi
3   4  444  xyz

In [44]:
display(df)

   id  sal  dep
0   1  444  abc
1   2  555  def
2   3  666  ghi
3   4  444  xyz

In [65]:
cols =['col1','col2','col3']
df.columns=cols
df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [66]:
df['col1']=df['col2'].astype("category")
df.dtypes

col1    category
col2       int64
col3      object
dtype: object

In [61]:
# df.head(1)

In [62]:
# df.tail(1)

In [63]:
# df.describe()

In [67]:
df.describe(include='category')

        col1
count      4
unique     3
top      444
freq       2

In [68]:
x=df.col2.idxmax()
x

2

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    4 non-null      category
 1   col2    4 non-null      int64
 2   col3    4 non-null      object
dtypes: category(1), int64(1), object(1)
memory usage: 332.0+ bytes

In [70]:
x=df.values
type(x)

numpy.ndarray

In [72]:
x=df.iloc[:,0:2]
print(x)
y=df.iloc[:,-1]
print("="*20)
print(y)

  col1  col2
0  444   444
1  555   555
2  666   666
3  444   444
====================
0    abc
1    def
2    ghi
3    xyz
Name: col3, dtype: object

In [73]:
df.drop(['col1','col2'],axis=1)

  col3
0  abc
1  def
2  ghi
3  xyz